micronaut:
    application:
        name: basketapp

jackson:
    serialization:
        indentOutput: true
        writeDatesAsTimestamps: false
    deserialization:
        useBigIntegerForInts: true
        failOnUnknownProperties: false

cassandra:
    default:
        clusterName: "${CASSANDRA_CLUSTERNAME:Test Cluster}"
        contactPoint: "${CASSANDRA_CONTACTPOINT:localhost}"
        port: "${CASSANDRA_PORT:9042}"
        maxSchemaAgreementWaitSeconds: 30
        ssl: false

elasticsearch:
    scheme: "${ELASTICSEARCH_SCHEME:http}"
    host: "${ELASTICSEARCH_HOST:localhost}"
    port: "${ELASTICSEARCH_PORT:9200}"
